In [50]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore') 
print("Libraries imported.")

Libraries imported.

In [51]:
from pathlib import Path
import os

data_path = Path('Dataset') / 'flights_data_raw.csv'
print("Working directory:", os.getcwd())
print("Looking for file:", data_path.resolve())

if not data_path.exists():
    raise FileNotFoundError(f"File not found: {data_path.resolve()} - check the path or working directory.")

try:
    df = pd.read_csv(data_path)
    print("Data loaded.")
    print("First 5 rows of the dataset:")
    print(df.head())
except OSError as e:
    # common fallback: try a different encoding/engine
    print("OSError while reading CSV:", e)
    try:
        df = pd.read_csv(data_path, encoding='latin-1', engine='python')
        print("Data loaded with fallback encoding/engine.")
        print(df.head())
    except Exception as e2:
        print("Fallback failed:", e2)
        raise

Working directory: p:\flight-delay-prediction-project
Looking for file: P:\flight-delay-prediction-project\Dataset\flights_data_raw.csv
Data loaded.
First 5 rows of the dataset:
   DayOfWeek        Date  DepTime  ArrTime  CRSArrTime UniqueCarrier  \
0          4  03-01-2019     1829     1959        1925            WN
1          4  03-01-2019     1937     2037        1940            WN
2          4  03-01-2019     1644     1845        1725            WN
3          4  03-01-2019     1452     1640        1625            WN
4          4  03-01-2019     1323     1526        1510            WN

                  Airline  FlightNum TailNum  ActualElapsedTime  ...  TaxiIn  \
0  Southwest Airlines Co.       3920  N464WN                 90  ...       3
1  Southwest Airlines Co.        509  N763SW                240  ...       3
2  Southwest Airlines Co.       1333  N334SW                121  ...       6
3  Southwest Airlines Co.        675  N286WN                228  ...       7
4  Southwest Airlines Co.          4  N674AA                123  ...       4

   TaxiOut  Cancelled  CancellationCode Diverted CarrierDelay WeatherDelay  \
0       10          0                 N        0            2            0
1        7          0                 N        0           10            0
2        8          0                 N        0            8            0
3        8          0                 N        0            3            0
4        9          0                 N        0            0            0

  NASDelay  SecurityDelay  LateAircraftDelay
0        0              0                 32
1        0              0                 47
2        0              0                 72
3        0              0                 12
4        0              0                 16

[5 rows x 29 columns]

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 484551 entries, 0 to 484550
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   DayOfWeek          484551 non-null  int64
 1   Date               484551 non-null  str
 2   DepTime            484551 non-null  int64
 3   ArrTime            484551 non-null  int64
 4   CRSArrTime         484551 non-null  int64
 5   UniqueCarrier      484551 non-null  str
 6   Airline            484551 non-null  str
 7   FlightNum          484551 non-null  int64
 8   TailNum            484551 non-null  str
 9   ActualElapsedTime  484551 non-null  int64
 10  CRSElapsedTime     484551 non-null  int64
 11  AirTime            484551 non-null  int64
 12  ArrDelay           484551 non-null  int64
 13  DepDelay           484551 non-null  int64
 14  Origin             484551 non-null  str
 15  Org_Airport        483374 non-null  str
 16  Dest               484551 non-null  str
 17  Dest_Airport       483072 non-null  str
 18  Distance           484551 non-null  int64
 19  TaxiIn             484551 non-null  int64
 20  TaxiOut            484551 non-null  int64
 21  Cancelled          484551 non-null  int64
 22  CancellationCode   484551 non-null  str
 23  Diverted           484551 non-null  int64
 24  CarrierDelay       484551 non-null  int64
 25  WeatherDelay       484551 non-null  int64
 26  NASDelay           484551 non-null  int64
 27  SecurityDelay      484551 non-null  int64
 28  LateAircraftDelay  484551 non-null  int64
dtypes: int64(20), str(9)
memory usage: 107.2 MB

In [53]:
df.shape

(484551, 29)

In [54]:
df.sample(5)

,DayOfWeek,Date,DepTime,ArrTime,CRSArrTime,UniqueCarrier,Airline,FlightNum,TailNum,ActualElapsedTime,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
266031,5,07-03-2019,1935,2256,2149,DL,Delta Air Lines Inc.,687,N910DL,201,...,14,20,0,N,0,5,0,30,0,32
379420,3,14-05-2019,1709,1759,1717,MQ,American Eagle Airlines Inc.,3333,N236AE,50,...,8,14,0,N,0,0,0,0,0,42
220431,2,18-03-2019,2110,2237,2134,US,US Airways Inc.,1755,N767UW,87,...,5,47,0,N,0,40,0,23,0,0
194994,2,25-03-2019,2153,105,20,WN,Southwest Airlines Co.,526,N265WN,132,...,4,7,0,N,0,0,0,0,0,45
449027,1,09-06-2019,1041,1404,1330,US,US Airways Inc.,71,N636AW,203,...,5,33,0,N,0,18,0,16,0,0

In [55]:
df.isnull().sum()

DayOfWeek               0
Date                    0
DepTime                 0
ArrTime                 0
CRSArrTime              0
UniqueCarrier           0
Airline                 0
FlightNum               0
TailNum                 0
ActualElapsedTime       0
CRSElapsedTime          0
AirTime                 0
ArrDelay                0
DepDelay                0
Origin                  0
Org_Airport          1177
Dest                    0
Dest_Airport         1479
Distance                0
TaxiIn                  0
TaxiOut                 0
Cancelled               0
CancellationCode        0
Diverted                0
CarrierDelay            0
WeatherDelay            0
NASDelay                0
SecurityDelay           0
LateAircraftDelay       0
dtype: int64

In [56]:
#Replacing Missing values of Org_Airport and Dest_Airport with most frequent values
df['Org_Airport'] = df['Org_Airport'].fillna(df['Org_Airport'].mode()[0])
df['Dest_Airport'] = df['Dest_Airport'].fillna(df['Dest_Airport'].mode()[0])

In [57]:
df.isnull().sum()

DayOfWeek            0
Date                 0
DepTime              0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
Airline              0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Org_Airport          0
Dest                 0
Dest_Airport         0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [58]:
print(df.columns)

Index(['DayOfWeek', 'Date', 'DepTime', 'ArrTime', 'CRSArrTime',
       'UniqueCarrier', 'Airline', 'FlightNum', 'TailNum', 'ActualElapsedTime',
       'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Origin',
       'Org_Airport', 'Dest', 'Dest_Airport', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='str')

In [59]:
columns_to_drop = ['UniqueCarrier', 'FlightNum', 'TailNum', 'TaxiIn', 'TaxiOut','Cancelled', 'CancellationCode', 'Diverted']
df = df.drop(columns=columns_to_drop)

In [60]:
print(df.columns)

Index(['DayOfWeek', 'Date', 'DepTime', 'ArrTime', 'CRSArrTime', 'Airline',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Org_Airport', 'Dest', 'Dest_Airport', 'Distance',
       'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay',
       'LateAircraftDelay'],
      dtype='str')

In [61]:
df_balanced = df.groupby('Airline').sample(frac=0.4, random_state=42)

In [62]:
df_balanced.shape

(193820, 21)

In [63]:
df = df_balanced

In [64]:
df.sample(5)

,DayOfWeek,Date,DepTime,ArrTime,CRSArrTime,Airline,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,...,Origin,Org_Airport,Dest,Dest_Airport,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
170048,5,08-02-2019,1916,2028,1935,American Airlines Inc.,192,195,175,53,...,DFW,Dallas/Fort Worth International Airport,LAX,Los Angeles International Airport,1235,53,0,0,0,0
349070,5,23-05-2019,1924,2139,2045,Southwest Airlines Co.,195,185,182,54,...,STL,St. Louis International Airport at Lambert Field,SLC,Salt Lake City International Airport,1156,3,0,10,0,41
44823,3,30-01-2019,1949,2218,2156,US Airways Inc.,149,166,133,22,...,PHL,Philadelphia International Airport,PBI,Palm Beach International Airport,951,0,0,0,0,22
376758,4,08-05-2019,2041,2216,2154,Atlantic Southeast Airlines,95,88,61,22,...,ATL,Hartsfield-Jackson Atlanta International Airport,EWN,Coastal Carolina Regional Airport (Craven Coun...,433,15,0,7,0,0
65100,5,04-01-2019,2119,2317,2215,American Eagle Airlines Inc.,58,60,35,62,...,ORD,Chicago O'Hare International Airport,TOL,Toledo Express Airport,214,62,0,0,0,0

In [65]:
df.drop_duplicates(inplace=True)

In [66]:
df.corr(numeric_only=True)

,DayOfWeek,DepTime,ArrTime,CRSArrTime,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
DayOfWeek,1.000000,0.017294,0.007304,0.011972,0.008208,0.012956,0.011811,-0.001130,0.004549,0.015568,0.019534,0.001942,-0.025291,0.008430,-0.001938
DepTime,0.017294,1.000000,0.362097,0.700642,-0.073582,-0.056888,-0.068074,0.104237,0.130573,-0.065321,-0.044185,-0.000466,0.002701,-0.020582,0.188154
ArrTime,0.007304,0.362097,1.000000,0.499032,-0.036210,-0.038480,-0.038985,-0.071068,-0.073524,-0.052822,-0.075205,-0.025691,0.033167,-0.011000,-0.040182
CRSArrTime,0.011972,0.700642,0.499032,1.000000,0.011185,0.024224,0.012791,0.028706,0.045336,0.013796,-0.088511,-0.019635,-0.009153,-0.017103,0.143345
ActualElapsedTime,0.008208,-0.073582,-0.036210,0.011185,1.000000,0.970044,0.975680,0.089366,0.007902,0.951035,0.029289,-0.007964,0.169165,0.002229,-0.031376
CRSElapsedTime,0.012956,-0.056888,-0.038480,0.024224,0.970044,1.000000,0.986562,0.039918,0.035497,0.983529,0.045224,-0.027264,0.046684,0.002967,-0.010797
AirTime,0.011811,-0.068074,-0.038985,0.012791,0.975680,0.986562,1.000000,0.039399,0.010356,0.977315,0.037608,-0.026301,0.068884,0.003828,-0.022086
ArrDelay,-0.001130,0.104237,-0.071068,0.028706,0.089366,0.039918,0.039399,1.000000,0.949397,0.027069,0.470913,0.273891,0.400464,-0.008335,0.502775
DepDelay,0.004549,0.130573,-0.073524,0.045336,0.007902,0.035497,0.010356,0.949397,1.000000,0.026527,0.497750,0.254128,0.243093,-0.007630,0.538781
Distance,0.015568,-0.065321,-0.052822,0.013796,0.951035,0.983529,0.977315,0.027069,0.026527,1.000000,0.046820,-0.030323,0.023205,0.003073,-0.010496
CarrierDelay,0.019534,-0.044185,-0.075205,-0.088511,0.029289,0.045224,0.037608,0.470913,0.497750,0.046820,1.000000,-0.059820,-0.110477,-0.020401,-0.186041
WeatherDelay,0.001942,-0.000466,-0.025691,-0.019635,-0.007964,-0.027264,-0.026301,0.273891,0.254128,-0.030323,-0.059820,1.000000,-0.001004,-0.007489,-0.049149
NASDelay,-0.025291,0.002701,0.033167,-0.009153,0.169165,0.046684,0.068884,0.400464,0.243093,0.023205,-0.110477,-0.001004,1.000000,-0.012624,-0.113077
SecurityDelay,0.008430,-0.020582,-0.011000,-0.017103,0.002229,0.002967,0.003828,-0.008335,-0.007630,0.003073,-0.020401,-0.007489,-0.012624,1.000000,-0.021477
LateAircraftDelay,-0.001938,0.188154,-0.040182,0.143345,-0.031376,-0.010797,-0.022086,0.502775,0.538781,-0.010496,-0.186041,-0.049149,-0.113077,-0.021477,1.000000

In [67]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [68]:
# Extract parts of Date
df['Month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek + 1   # Monday=1, Sunday=7
df['DayName'] = df['Date'].dt.day_name()

In [69]:
# Make a copy to be safe
df2 = df.copy()

# ---------- helper: ensure numeric where needed ----------
num_cols = ['ActualElapsedTime','Distance','ArrDelay','DepDelay',
            'CarrierDelay','WeatherDelay','NASDelay','SecurityDelay','LateAircraftDelay']

for c in num_cols:
    if c in df2.columns:
        df2[c] = pd.to_numeric(df2[c], errors='coerce')  # coerce bad values to NaN

In [70]:
# ----------  Route column = Origin + "_" + Dest ----------
if ('Origin' in df2.columns) and ('Dest' in df2.columns):
    df2['Route'] = df2['Origin'].astype(str) + '_' + df2['Dest'].astype(str)
else:
    print("Warning: 'Origin' and/or 'Dest' not in dataframe; skipping Route creation")

In [71]:
#----------  speed = distance (miles) / time(min) ----------
if ('Distance' in df2.columns) and ('ActualElapsedTime' in df2.columns):
    # Avoid division by zero
    df2['ActualElapsedTime'] = df2['ActualElapsedTime'].replace(0, np.nan)
    
    # Speed in miles per minute
    df2['Speed_miles_per_min'] = df2['Distance'] / df2['ActualElapsedTime']
else:
    print("Warning: 'Distance' and/or 'ActualElapsedTime' missing; skipping Speed")

In [72]:
# ---------- TotalDelay = sum of all reason-specific delays (safer target) ----------
delay_reason_cols = [c for c in ['CarrierDelay','WeatherDelay','NASDelay','SecurityDelay','LateAircraftDelay'] if c in df2.columns]
if delay_reason_cols:
    df2['TotalDelay'] = df2[delay_reason_cols].fillna(0).sum(axis=1)
else:
    print("Warning: no reason-specific delay columns found; skipping TotalDelay")
    
# ---------- DelayPerDistance = TotalDelay / Distance ----------
if ('TotalDelay' in df2.columns) and ('Distance' in df2.columns):
    df2['DelayPerDistance'] = (df2['TotalDelay'])/ df2['Distance'].replace(0, np.nan)
else:
    print("Warning: 'TotalDelay' and/or 'Distance' missing; skipping DelayPerDistance")

In [73]:
df2.sample(5)

,DayOfWeek,Date,DepTime,ArrTime,CRSArrTime,Airline,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,...,NASDelay,SecurityDelay,LateAircraftDelay,Month,day,DayName,Route,Speed_miles_per_min,TotalDelay,DelayPerDistance
77418,4,2019-01-24,1929,2057,1945,American Airlines Inc.,88,80,72,72,...,72,0,0,1,24,Thursday,LAX_SFO,3.829545,72,0.213650
445407,1,2019-06-03,1953,2246,2153,United Air Lines Inc.,113,128,95,53,...,0,0,53,6,3,Monday,ORD_BDL,6.929204,53,0.067688
138291,2,2019-02-26,636,1006,817,Delta Air Lines Inc.,210,137,155,109,...,73,0,0,2,26,Tuesday,ROC_ATL,3.566667,109,0.145527
53355,5,2019-01-11,626,909,848,Atlantic Southeast Airlines,163,153,120,21,...,21,0,0,1,11,Friday,ACY_ATL,4.159509,21,0.030973
448948,7,2019-06-09,2258,651,610,US Airways Inc.,293,320,278,41,...,0,0,32,6,9,Sunday,LAX_PHL,8.194539,41,0.017076

In [74]:
columns_to_drop = ['ActualElapsedTime', 'CRSElapsedTime', 'AirTime','Origin', 'Dest',
                   'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay','LateAircraftDelay']
df2 = df2.drop(columns=columns_to_drop)

In [75]:
df2.shape

(193820, 18)

In [76]:
df2.columns

Index(['DayOfWeek', 'Date', 'DepTime', 'ArrTime', 'CRSArrTime', 'Airline',
       'ArrDelay', 'DepDelay', 'Org_Airport', 'Dest_Airport', 'Distance',
       'Month', 'day', 'DayName', 'Route', 'Speed_miles_per_min', 'TotalDelay',
       'DelayPerDistance'],
      dtype='str')

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier
from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import classification_report, accuracy_score, r2_score, mean_absolute_error, mean_squared_error, roc_auc_score, precision_recall_curve, f1_score
import time
import warnings
warnings.filterwarnings('ignore')

In [78]:
newdf = df2.copy()

In [79]:
# Delay if arrival delay > 15 minutes
newdf['IsDelayed'] = (newdf['ArrDelay'] > 15).astype(int)

In [80]:
cols_to_drop = [
    'ArrDelay',              # target (don’t use in X)
    'TotalDelay',            # post-flight info
    'DelayPerDistance',      # derived from delay
    'Speed_miles_per_min',   # uses actual time
    'ArrTime',               # post-flight
    'CRSArrTime'             # near target info
]

newdf = newdf.drop(columns=[c for c in cols_to_drop if c in newdf.columns])

In [81]:
import numpy as np

# Log distance (handles long flight effect better)
newdf['log_Distance'] = np.log1p(newdf['Distance'])

# Weekend feature
newdf['IsWeekend'] = newdf['DayOfWeek'].isin([6,7]).astype(int)

In [82]:
features = [
    'DepDelay',
    'Distance',
    'log_Distance',
    'Month',
    'DayOfWeek',
    'DepTime',
    'IsWeekend',  
]

X = newdf[features]
y = newdf['IsDelayed']

In [83]:
X = X.fillna(0)
y = y.fillna(0)

In [84]:
print(y.value_counts())

IsDelayed
1    188544
0      5276
Name: count, dtype: int64

In [85]:
from sklearn.utils import resample

df_temp = X.copy()
df_temp['target'] = y

# Separate classes
df_0 = df_temp[df_temp['target'] == 0]
df_1 = df_temp[df_temp['target'] == 1]

# Find minority size
min_size = min(len(df_0), len(df_1))

# Downsample both to same size
df_0_down = df_0.sample(n=min_size, random_state=42)
df_1_down = df_1.sample(n=min_size, random_state=42)

# Combine
df_bal = pd.concat([df_0_down, df_1_down])

# Shuffle
df_bal = df_bal.sample(frac=1, random_state=42)

# Split back
X = df_bal.drop('target', axis=1)
y = df_bal['target']

In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [87]:
from xgboost import XGBClassifier

delay_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

delay_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [88]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = delay_model.predict(X_test)
y_prob = delay_model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7915679772619612
              precision    recall  f1-score   support

           0       0.75      0.89      0.81      1072
           1       0.86      0.69      0.76      1039

    accuracy                           0.79      2111
   macro avg       0.80      0.79      0.79      2111
weighted avg       0.80      0.79      0.79      2111

[[958 114]
 [326 713]]

In [89]:
y_pred_custom = (y_prob > 0.45).astype(int)

print(classification_report(y_test, y_pred_custom))
print(confusion_matrix(y_test, y_pred_custom))

              precision    recall  f1-score   support

           0       0.75      0.86      0.80      1072
           1       0.83      0.71      0.76      1039

    accuracy                           0.78      2111
   macro avg       0.79      0.78      0.78      2111
weighted avg       0.79      0.78      0.78      2111

[[918 154]
 [304 735]]

In [90]:
import pickle

with open('delay_classifier.pkl', 'wb') as f:
    pickle.dump(delay_model, f)

with open('delay_classifier_columns.pkl', 'wb') as f:
    pickle.dump(X.columns, f)